name: Build macOS Agent

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install stuff
      run: |
        cd agent
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build executable
      run: |
        cd agent
        pyinstaller --onefile --name devops-agent simple-agent.py
    
    - name: Test it works
      run: |
        cd agent/dist
        ./devops-agent --help
    
    - name: Make zip
      run: |
        cd agent/dist
        tar -czf devops-agent-macos.tar.gz devops-agent
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: macos-agent
        path: agent/dist/devops-agent-macos.tar.gz
