name: Build Agent Executables

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (like v1.0.0)'
        required: false
        default: 'dev'

permissions:
  contents: write
  packages: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install stuff
      run: |
        cd agent
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build executable
      run: |
        cd agent
        pyinstaller --onefile --name devops-agent simple-agent.py
    - name: Make zip
      run: |
        cd agent/dist
        Compress-Archive -Path devops-agent.exe -DestinationPath devops-agent-windows.zip
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: windows-agent
        path: agent/dist/devops-agent-windows.zip

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install stuff
      run: |
        cd agent
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build executable
      run: |
        cd agent
        pyinstaller --onefile --name devops-agent simple-agent.py
    - name: Make zip
      run: |
        cd agent/dist
        tar -czf devops-agent-macos.tar.gz devops-agent
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: macos-agent
        path: agent/dist/devops-agent-macos.tar.gz

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Download all the built stuff
    - name: Download Windows  
      uses: actions/download-artifact@v4
      with:
        name: windows-agent
        path: ./
    
    - name: Download macOS
      uses: actions/download-artifact@v4
      with:
        name: macos-agent
        path: ./
    
    # Make a release
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.version || 'dev' }}
        name: Agent ${{ github.event.inputs.version || 'dev' }}
        body: |
          ## DevOps Agent ${{ github.event.inputs.version || 'dev' }}
          
          ### 📥 Downloads
          
          **Windows & macOS Users:**
          - **Windows**: `devops-agent-windows.zip` - Ready-to-run executable
          - **macOS**: `devops-agent-macos.tar.gz` - Ready-to-run executable
          
          **Linux Users:**
          - Use the installation script: `./simple-install.sh` (from the source code)
          - Or run directly: `python3 simple-agent.py`
          
          ### 🚀 Quick Start
          
          **Windows/macOS:**
          1. Download and extract the file for your platform
          2. Double-click the executable or run from terminal
          3. Follow the interactive setup prompts
          
          **Linux:**
          1. Clone the repository or download the agent folder
          2. Run: `cd agent && ./simple-install.sh`
          3. Run: `python3 ~/.devops-agent/simple-agent.py`
          
          ### 💡 Usage
          ```bash
          # Interactive mode (recommended for beginners)
          ./devops-agent
          
          # Command line mode
          ./devops-agent --server http://your-server:8085 --once
          ```
        files: |
          devops-agent-windows.zip
          devops-agent-macos.tar.gz
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
