name: CI - Python

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff bandit pytest

      - name: Ruff (lint/format)
        run: |
          ruff check .
          ruff format --check .

      - name: Bandit (security)
        run: bandit -r app.py agent || true  # don't block initially

      - name: Pytest
        run: pytest -q || true  # keep green until tests exist