name: Security - Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: trufflesecurity/trufflehog-action@v3.90.8
        with:
          path: .
          extra_args: --skip-verification